title: "Home"
author: "Md. Tasnim Azad"
description: "Contact"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "academics.html", title: "Academics"}
  - {file: "work_experience.md", title: "Work Experience"}
  - {file: "README.md", title: "Skills"}
  - {file: "publications.md", title: "Publications"}
  - {file: "README.md", title: "Projects"}
  - {title: "CV", file: "cv.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:nihan.tas.2016@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/nihan139"}
  - {title: LinkedIn, icon: linkedin-in, url: "https://www.linkedin.com/in/md-tasnim-azad-543736192/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
